"""Agregado de tabla Cars

Revision ID: 6041ec0d6bab
Revises: [a484ca96a1f5]
Create Date: 2023-10-10 19:13:14.471791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6041ec0d6bab'
down_revision = '[a484ca96a1f5]'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
